---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Role and IAM Policy for Datadog AWS Integration'
Outputs:
  DatadogAccountID:
    Value:
      Ref: DatadogAccountID
  #DatadogExternalID:
  #  Value:
  #    Ref: DatadogExternalID
  PolicyArn:
    Value:
      Ref: DatadogAWSIntegrationPolicy
  RoleName:
    Value:
      Ref: DatadogAWSIntegrationRole
Parameters:
  DatadogAccountID:
    Default: '464622532012'
    Description: "Datadog's account ID (Ref: https://docs.datadoghq.com/integrations/amazon_web_services/)"
    Type: String
  DatadogExternalID:
    Default: YourExternalID
    Description: External ID generate by Datadog (https://app.datadoghq.com/account/settings#integrations/amazon_web_services)
    Type: String
    NoEcho: 'true'
  PermissionLevel:
    Default: full
    AllowedValues:
    - full
    - minimum
    Description: Select permission to grant to IAM Role
    Type: String
  PermissionsFull:
    # Delete double quotes(") after copy & paste from doc (#installation)
    Default: >-
        autoscaling:Describe*,
        budgets:ViewBudget,
        cloudfront:GetDistributionConfig,
        cloudfront:ListDistributions,
        cloudtrail:DescribeTrails,
        cloudtrail:GetTrailStatus,
        cloudwatch:Describe*,
        cloudwatch:Get*,
        cloudwatch:List*,
        codedeploy:List*,
        codedeploy:BatchGet*,
        directconnect:Describe*,
        dynamodb:List*,
        dynamodb:Describe*,
        ec2:Describe*,
        ecs:Describe*,
        ecs:List*,
        elasticache:Describe*,
        elasticache:List*,
        elasticfilesystem:DescribeFileSystems,
        elasticfilesystem:DescribeTags,
        elasticloadbalancing:Describe*,
        elasticmapreduce:List*,
        elasticmapreduce:Describe*,
        es:ListTags,
        es:ListDomainNames,
        es:DescribeElasticsearchDomains,
        health:DescribeEvents,
        health:DescribeEventDetails,
        health:DescribeAffectedEntities,
        kinesis:List*,
        kinesis:Describe*,
        lambda:AddPermission,
        lambda:GetPolicy,
        lambda:List*,
        lambda:RemovePermission,
        logs:Get*,
        logs:Describe*,
        logs:FilterLogEvents,
        logs:TestMetricFilter,
        logs:PutSubscriptionFilter,
        logs:DeleteSubscriptionFilter,
        logs:DescribeSubscriptionFilters,
        rds:Describe*,
        rds:List*,
        redshift:DescribeClusters,
        redshift:DescribeLoggingStatus,
        route53:List*,
        s3:GetBucketLogging,
        s3:GetBucketLocation,
        s3:GetBucketNotification,
        s3:GetBucketTagging,
        s3:ListAllMyBuckets,
        s3:PutBucketNotification,
        ses:Get*,
        sns:List*,
        sns:Publish,
        sqs:ListQueues,
        support:DescribeTrustedAdvisorChecks,
        support:RefreshTrustedAdvisorCheck,
        support:DescribeTrustedAdvisorCheckResult,
        tag:GetResources,
        tag:GetTagKeys,
        tag:GetTagValues
    Type: CommaDelimitedList
  PermissionsMinimum:
    # Delete double quotes(") after copy & paste from doc (#permissions)
    Default: >-
        cloudwatch:Get*,
        cloudwatch:List*,
        ec2:Describe*,
        support:*,
        tag:GetResources,
        tag:GetTagKeys,
        tag:GetTagValues
    Type: CommaDelimitedList
Conditions:
  Permissions:
    Fn::Equals:
    - Ref: PermissionLevel
    - full
Resources:
  DatadogAWSIntegrationPolicy:
    Properties:
      PolicyDocument:
        Statement:
        - Action:
            Fn::If:
            - Permissions
            - Ref: PermissionsFull
            - Ref: PermissionsMinimum
          Effect: Allow
          Resource: "*"
        Version: '2012-10-17'
      Roles:
      - Ref: DatadogAWSIntegrationRole
      # When you want to give a specific name
      #ManagedPolicyName: "DatadogAWSIntegrationRolePolicy"
    Type: AWS::IAM::ManagedPolicy
  DatadogAWSIntegrationRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId:
                Ref: DatadogExternalID
          Effect: Allow
          Principal:
            AWS:
              Fn::Sub: arn:aws:iam::${DatadogAccountID}:root
        Version: '2012-10-17'
      # When you want to give a specific name
      #RoleName: 'DatadogAWSIntegrationRole'
    Type: AWS::IAM::Role
